version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  web:
    build: .
    container_name: web
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://shop_user:shop_password@badminton-shop-cluster.wcjjhqv.mongodb.net/?retryWrites=true&w=majority&appName=badminton-shop-cluster
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongodb_data:
