version: '3.8'

services:
  web:
    build: .
    container_name: web
    environment:
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - ./public/images:/app/public/images
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      web:
        condition: service_healthy
    restart: unless-stopped
